// @flow

export const ACTION_FETCH_BOOK_DETAILS = "ACTION_FETCH_BOOK_DETAILS";
export const ACTION_FETCH_BOOK_CHAPTER_LIST = "ACTION_FETCH_BOOK_CHAPTER_LIST";
export const ACTION_CHANGE_DISPLAY_PAGE = "ACTION_CHANGE_DISPLAY_PAGE";
export const ACTION_CHANGE_CHECKBOX_STATUS = "ACTION_CHANGE_CHECKBOX_STATUS";
export const ACTION_FETCH_TOPIC_DETAILS = "ACTION_FETCH_TOPIC_DETAILS";
export const ACTION_SET_CURRENT_TOPIC = "ACTION_SET_CURRENT_TOPIC_DETAILS";
export const ACTION_SET_CURRENT_CHAPTER = "ACTION_SET_CURRENT_CHAPTER";
