// @flow

export const ACTION_FETCH_BOOK_DETAILS = "ACTION_FETCH_BOOK_DETAILS";
export const ACTION_FETCH_BOOK_CHAPTER_LIST = "ACTION_FETCH_BOOK_CHAPTER_LIST";
export const ACTION_CHANGE_DISPLAY_PAGE = "ACTION_CHANGE_DISPLAY_PAGE";
